-- ====================================================================
-- DDL STATEMENTS FOR ALL 21 BRONZE TABLES (TRACK 2 - LOAN CONTRACT)
-- ====================================================================

-- Group A: Core tables for LOAN_AR / LOAN_AR_PRFL (14 tables)
CREATE TABLE IF NOT EXISTS demo.default.bz_t24core_ld_loans_and_deposits (
    RECID STRING, AMOUNT STRING, CUSTOMER_ID STRING, CO_CODE STRING,
    PRIN_LIQ_ACCT STRING, INT_LIQ_ACCT STRING, DRAWDOWN_NET_AMT STRING,
    ORIG_VAL_DATE STRING, VALUE_DATE STRING, FIN_MAT_DATE STRING,
    INT_RATE_TYPE STRING, INTEREST_SPREAD STRING, INTEREST_RATE STRING,
    REAL_RATE STRING, CATEGORY STRING, APPROVE_AMOUNT STRING,
    DATE_TIME STRING, CURR_NO STRING, ACC_FCC STRING, CURRENCY STRING,
    RECORD_STATUS STRING, INT_VALUE_DATE STRING, USE_OF_LOAN STRING,
    USE_OF_LOAN_CHA STRING, CRA_LD STRING, EXCG_RATE STRING,
    MB_RM_BANCHEO STRING, LOC_TERM STRING, COMMIT_ACTION STRING,
    AUTHORISER STRING, INPUTTER STRING, LOS_FAC_CODE STRING,
    ORIGINAL_MAT STRING, PRODUCTGR_CODE STRING, FCC_LIMIT STRING,
    STATUS STRING, LIMIT_REFERENCE STRING, PE_RATE STRING, PS_RATE STRING,
    BRZ_LOAD_DT TIMESTAMP, SRC_SYSTEM STRING, ETL_BATCH_ID STRING
) USING parquet LOCATION 's3a://bronze/bz_t24core_ld_loans_and_deposits/';

CREATE TABLE IF NOT EXISTS demo.default.bz_t24core_ld_loans_and_deposits_his (
    RECID STRING, AMOUNT STRING, CUSTOMER_ID STRING, CO_CODE STRING,
    PRIN_LIQ_ACCT STRING, INT_LIQ_ACCT STRING, DRAWDOWN_NET_AMT STRING,
    ORIG_VAL_DATE STRING, VALUE_DATE STRING, FIN_MAT_DATE STRING,
    INT_RATE_TYPE STRING, INTEREST_SPREAD STRING, INTEREST_RATE STRING,
    REAL_RATE STRING, CATEGORY STRING, APPROVE_AMOUNT STRING,
    DATE_TIME STRING, CURR_NO STRING, ACC_FCC STRING, CURRENCY STRING,
    RECORD_STATUS STRING, INT_VALUE_DATE STRING, USE_OF_LOAN STRING,
    USE_OF_LOAN_CHA STRING, CRA_LD STRING, EXCG_RATE STRING,
    MB_RM_BANCHEO STRING, LOC_TERM STRING, COMMIT_ACTION STRING,
    AUTHORISER STRING, INPUTTER STRING, LOS_FAC_CODE STRING,
    ORIGINAL_MAT STRING, PRODUCTGR_CODE STRING, FCC_LIMIT STRING,
    STATUS STRING, LIMIT_REFERENCE STRING, PE_RATE STRING, PS_RATE STRING,
    BRZ_LOAD_DT TIMESTAMP, SRC_SYSTEM STRING, ETL_BATCH_ID STRING
) USING parquet LOCATION 's3a://bronze/bz_t24core_ld_loans_and_deposits_his/';

CREATE TABLE IF NOT EXISTS demo.default.bz_flexbo_pgb_ldtb_contract_master (
    CONTRACT_REF_NO STRING, VERSION_NO STRING, BOOKING_DATE STRING,
    BRZ_LOAD_DT TIMESTAMP, SRC_SYSTEM STRING, ETL_BATCH_ID STRING
) USING parquet LOCATION 's3a://bronze/bz_flexbo_pgb_ldtb_contract_master/';

CREATE TABLE IF NOT EXISTS demo.default.bz_flexbo_pgb_los_contract_fields_tdate (
    CONTRACT_REF_NO STRING, MOV_DATE STRING, BIEN_DO_THAY_DOI_LS_THEO_HDTD STRING,
    SAN_PHAM_CHO_VAY_KHCN STRING, SAN_PHAM_CHO_VAY_KHDN STRING, MDVAY_SP STRING,
    SO_LAN_CO_CAU STRING, CAR_APPLICATION_CODE STRING, LOS_CONTRACT_CODE STRING,
    LOS_CONTRACT_ID STRING, CO_CAU_NO_MIEN_GIAM_LAI STRING, MDVAY_NKT STRING,
    CAN_BO_DE_XUAT_GN STRING, TT_PP_DE_XUAT_GN STRING, CBTD_QL_KHOAN_VAY STRING,
    TP_PP_QL_KHOAN_VAY STRING, CAP_PHE_DUYET_GNTL STRING,
    BRZ_LOAD_DT TIMESTAMP, SRC_SYSTEM STRING, ETL_BATCH_ID STRING
) USING parquet LOCATION 's3a://bronze/bz_flexbo_pgb_los_contract_fields_tdate/';

CREATE TABLE IF NOT EXISTS demo.default.bz_los_app_loan_disbursement (
    ID STRING, EXT_REF_NO_1 STRING, AMND_STATE STRING, STATUS STRING,
    FACILITY_ID STRING, BOOKING_DATE STRING,
    BRZ_LOAD_DT TIMESTAMP, SRC_SYSTEM STRING, ETL_BATCH_ID STRING
) USING parquet LOCATION 's3a://bronze/bz_los_app_loan_disbursement/';

CREATE TABLE IF NOT EXISTS demo.default.bz_los_app_facility (
    ID STRING, PRODUCT_ID STRING,
    BRZ_LOAD_DT TIMESTAMP, SRC_SYSTEM STRING, ETL_BATCH_ID STRING
) USING parquet LOCATION 's3a://bronze/bz_los_app_facility/';

CREATE TABLE IF NOT EXISTS demo.default.bz_los_app_product (
    ID STRING, PRODUCT_CODE STRING,
    BRZ_LOAD_DT TIMESTAMP, SRC_SYSTEM STRING, ETL_BATCH_ID STRING
) USING parquet LOCATION 's3a://bronze/bz_los_app_product/';

CREATE TABLE IF NOT EXISTS demo.default.bz_t24core_customer (
    RECID STRING, KHOI STRING,
    BRZ_LOAD_DT TIMESTAMP, SRC_SYSTEM STRING, ETL_BATCH_ID STRING
) USING parquet LOCATION 's3a://bronze/bz_t24core_customer/';

CREATE TABLE IF NOT EXISTS demo.default.bz_ebanking_col_udf_value (
    COL_REF STRING, FUNCTION_CODE STRING, UDF_ID STRING, UDF_VALUE STRING,
    BRZ_LOAD_DT TIMESTAMP, SRC_SYSTEM STRING, ETL_BATCH_ID STRING
) USING parquet LOCATION 's3a://bronze/bz_ebanking_col_udf_value/';

CREATE TABLE IF NOT EXISTS demo.default.bz_flexbo_pgb_contract_udf_map (
    CONTRACT_REF_NO STRING, FIELD_NAME STRING, FIELD_VAL STRING,
    BRZ_LOAD_DT TIMESTAMP, SRC_SYSTEM STRING, ETL_BATCH_ID STRING
) USING parquet LOCATION 's3a://bronze/bz_flexbo_pgb_contract_udf_map/';

CREATE TABLE IF NOT EXISTS demo.default.bz_flexbo_pgbld_contract_udfield_hist (
    CONTRACT_REF_NO STRING, CT_KHUYEN_MAI_CHO_VAY STRING, CTKM2 STRING,
    BRZ_LOAD_DT TIMESTAMP, SRC_SYSTEM STRING, ETL_BATCH_ID STRING
) USING parquet LOCATION 's3a://bronze/bz_flexbo_pgbld_contract_udfield_hist/';

CREATE TABLE IF NOT EXISTS demo.default.bz_t24core_mb_mg_saving_multi (
    LD_ID STRING, MB_LD_TYPE STRING,
    BRZ_LOAD_DT TIMESTAMP, SRC_SYSTEM STRING, ETL_BATCH_ID STRING
) USING parquet LOCATION 's3a://bronze/bz_t24core_mb_mg_saving_multi/';

CREATE TABLE IF NOT EXISTS demo.default.bz_flexbo_pgbld_rt_contract_udfield_hist (
    CONTRACT_REF_NO STRING, CO_CAU_NO STRING, NGAY_HET_COVID19 STRING,
    BRZ_LOAD_DT TIMESTAMP, SRC_SYSTEM STRING, ETL_BATCH_ID STRING
) USING parquet LOCATION 's3a://bronze/bz_flexbo_pgbld_rt_contract_udfield_hist/';

CREATE TABLE IF NOT EXISTS demo.default.bz_source_saoke_mvmt (
    TRANS_REF STRING, SBV_CODE STRING,
    BRZ_LOAD_DT TIMESTAMP, SRC_SYSTEM STRING, ETL_BATCH_ID STRING
) USING parquet LOCATION 's3a://bronze/bz_source_saoke_mvmt/';

-- Group B: Tables for Satellite tables (7 tables)
CREATE TABLE IF NOT EXISTS demo.default.bz_source_saoke_crb (
    APP_ID STRING, APP_CODE STRING, CUSTOMER_ID STRING, AMOUNT_CUR STRING,
    AMOUNT_LCY STRING, ASSET_TYPE STRING, CATEG_CODE STRING, CO_CODE STRING,
    CURR STRING, CUS_ID STRING, LOC_TERM STRING, SBV_CODE STRING,
    SUB_PRO STRING, TXN_DATE STRING,
    BRZ_LOAD_DT TIMESTAMP, SRC_SYSTEM STRING, ETL_BATCH_ID STRING
) USING parquet LOCATION 's3a://bronze/bz_source_saoke_crb/';

CREATE TABLE IF NOT EXISTS demo.default.bz_t24core_stmt_entry (
    RECID STRING, OUR_REFERENCE STRING, TRANSACTION_CODE STRING,
    CRF_PROD_CAT STRING, CURRENCY STRING, AMOUNT_LCY STRING, AMOUNT_FCY STRING,
    BOOKING_DATE STRING,
    BRZ_LOAD_DT TIMESTAMP, SRC_SYSTEM STRING, ETL_BATCH_ID STRING
) USING parquet LOCATION 's3a://bronze/bz_t24core_stmt_entry/';

CREATE TABLE IF NOT EXISTS demo.default.bz_t24core_pd_payment_due_his_mv (
    RECID STRING, PAY_TYPE STRING, FLAG_STATUS STRING, RECORD_STATUS STRING,
    PAY_AMT_OUTS STRING, DATE_TIME STRING, CURR_NO STRING, CATEGORY STRING,
    PAYMENT_DTE_DUE STRING, PD_TYPE STRING,
    BRZ_LOAD_DT TIMESTAMP, SRC_SYSTEM STRING, ETL_BATCH_ID STRING
) USING parquet LOCATION 's3a://bronze/bz_t24core_pd_payment_due_his_mv/';

CREATE TABLE IF NOT EXISTS demo.default.bz_t24core_pd_payment_due (
    RECID STRING, SNQH_CHUYENDOI STRING,
    BRZ_LOAD_DT TIMESTAMP, SRC_SYSTEM STRING, ETL_BATCH_ID STRING
) USING parquet LOCATION 's3a://bronze/bz_t24core_pd_payment_due/';

CREATE TABLE IF NOT EXISTS demo.default.bz_t24core_company (
    RECID STRING, COMPANY_NAME STRING,
    BRZ_LOAD_DT TIMESTAMP, SRC_SYSTEM STRING, ETL_BATCH_ID STRING
) USING parquet LOCATION 's3a://bronze/bz_t24core_company/';

CREATE TABLE IF NOT EXISTS demo.default.bz_pg_t24core_currency (
    ID STRING, MID_REVAL_RATE STRING, DATE_TIME STRING,
    BRZ_LOAD_DT TIMESTAMP, SRC_SYSTEM STRING, ETL_BATCH_ID STRING
) USING parquet LOCATION 's3a://bronze/bz_pg_t24core_currency/';

CREATE TABLE IF NOT EXISTS demo.default.bz_pg_t24core_currency_his (
    ID STRING, MID_REVAL_RATE STRING, DATE_TIME STRING, CURR_NO STRING,
    BRZ_LOAD_DT TIMESTAMP, SRC_SYSTEM STRING, ETL_BATCH_ID STRING
) USING parquet LOCATION 's3a://bronze/bz_pg_t24core_currency_his/';
